### PR TITLE
Fix regression around column resize state being retained too aggresively

### LINKED ISSUE #276: Column resize problems
Our grid is configured to allow column resizing, and we put a dropdown menu in each column header, which gives options for re-sorting based on that column.

The following works correctly for us with fixed-data-table-2 release 0.7.17. But in release 0.8.8, we observe the following problems:

# Problem 1
## Expected Behavior
Drag the edge of a column header, right or left: the column should resize to the width you specified.
Click any other column header: the dropdown appears, the previously resized column should be unchanged.

## Current Behavior
Drag the edge of a column header, right or left: the column resizes correctly.
Click any other column header:  the dropdown appears, but the previously resized column resets to a minimum width.

# Problem 2
## Expected Behavior
Drag the edge of a column header, right or left: the column should resize to the width you specified.
Drag the edge of a different column header, right or left: the blue line should follow the cursor.

## Current Behavior
Drag the edge of a column header, right or left: the column resizes correctly.
Drag the edge of a different column header, right or left: the blue line is offset from the cursor, apparently by the distance between the two columns.

# Problem 3
## Expected Behavior
Drag the edge of a column header, right or left: the column should resize to the width you specified.
Drag the edge of a different column header, right or left: the column should resize to the width you specified.
Click any other column header: the dropdown appears, the previously resized columns should be unchanged.

## Current Behavior
Drag the edge of a column header, right or left: the column resizes correctly.
Drag the edge of a different column header, right or left: the column resizes correctly.
Click any other column header: the dropdown appears, but the second resized column (but not the first) resets to a minimum width.

## Context
These problems do not occur in release 0.7.17, but they do occur in release 0.8.8, so we cannot update. We would like to update because we need column resize on touch devices, but we can't.

## Your Environment
* Version used: 0.8.8
* Browser Name and version: Chrome Version 63.0.3239.132 (Official Build) (64-bit), Firefox 57.0.1 (64-bit)
* Operating System and version (desktop or mobile): macOS 10.13.2
* Link to your project: (not public)

### PR DESCRIPTION
**Pull request by wcjordan**
Only retain when the prop is undefined, not when explicitly set to false.

@miskreant @quixotically could one of you take a look when you get a chance?

## Description

#276 is happening because we're retaining the old column state even when resizing is stopped.

## Motivation and Context

Fix #276 

## How Has This Been Tested?

Tested on the test case from #268 and the column resize example.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: examples/ObjectDataExample.js [hunk 1]
```diff
@@ -9,109 +9,78 @@ const { DateCell, ImageCell, LinkCell, TextCell } = require('./helpers/cells');
 const { Table, Column, Cell } = require('fixed-data-table-2');
 const React = require('react');
```
Comment (wcjordan) [inline examples/ObjectDataExample.js]: You can ignore changes in this file.  I accidentally committed when working on #268.  Reverting now

File: src/FixedDataTable.js [hunk 2]
```diff
@@ -1177,7 +1177,9 @@ var FixedDataTable = createReactClass({
     }
 
     var columnResizingData;
-    if (props.isColumnResizing || (oldState && oldState.isColumnResizing)) {
```
Comment (wcjordan) [inline src/FixedDataTable.js]: Just adding the props.isColumnResizing === undefined condition here so we only use oldState when isColumnResizing is not specified in the props.
