### PR TITLE
Multi table fix

### LINKED ISSUE #369: Focus jumps when I have two tables on the same screen and scroll the above table
The version "1.0.0-beta.5" has the following bug:
When I have 2 tables on the same page, focus the bottom one, scroll the top one and then try to write something on the bottom table (which still has the focus on), the focus jumps all over the place.

Like this:
bug

## Your Environment
* Version used: 1.0.0-beta.5
* Browser Name and version: Chrome latest
* Operating System and version (desktop or mobile): mac desktop
* Link to your project: https://github.com/Powerade/fixed-data-table-2-bugs/tree/focus-bug-double-table

### PR DESCRIPTION
**Pull request by wcjordan**
## Description

Re-initialize the initial state with each FDT instance.  Fixes #369 

## Motivation and Context

See #369 

## How Has This Been Tested?

Added a 2nd table to an example with input fields.  Tested #369 no longer occurs when typing in an input after scrolling the other table

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: src/reducers/index.js [hunk 1]
```diff
@@ -21,84 +21,86 @@ import convertColumnElementsToData from 'convertColumnElementsToData';
...
-  isColumnResizing: false,
-  maxScrollX: 0,
-  maxScrollY: 0,
-  rowHeights: {},
-  rows: [], // rowsToRender
-  scrollContentHeight: 0,
-  scrollX: 0,
-  scrollY: 0,
-};
+function getInitialState() {
```
Comment (wcjordan) [inline src/reducers/index.js]: Internals here are unchanged.  Just moved the consts within the function.

Comment (pradeepnschrodinger) [reply src/reducers/index.js]: Would it be better to assign getInitialState to a function defined within a function which also contains the immutable constants, so that they aren't recalculated, but simply reused for every function call.

something like: 
```javascript
const getInitialState = (function() {
    const DEFAULT_INPUT_STATE = {...};
    const DEFAULT_OUTPUT_STATE = {...};
    const DEFAULT_INTERNAL_STATE = {...};
    const INITIAL_STATE = Object.assign({},
        DEFAULT_INPUT_STATE,
        DEFAULT_OUTPUT_STATE,
        DEFAULT_INTERNAL_STATE
    );
    return function() { return INITIAL_STATE };
 })();
```

Comment (wcjordan) [reply src/reducers/index.js]: Wouldn't that lead to the same bug where each call to getInitialState returned the same object?

Maybe the confusion is I should update the variable names so their no longer all caps, since these aren't global consts anymore?

Comment (pradeepnschrodinger) [reply src/reducers/index.js]: Ah yes it will, my bad. 
In that case, adding a cloneDeep should suffice.
```javascript
const getInitialState = (function() {
    const DEFAULT_INPUT_STATE = {...};
    const DEFAULT_OUTPUT_STATE = {...};
    const DEFAULT_INTERNAL_STATE = {...};
    const INITIAL_STATE = Object.assign({},
        DEFAULT_INPUT_STATE,
        DEFAULT_OUTPUT_STATE,
        DEFAULT_INTERNAL_STATE
    );
    return function() { return _.cloneDeep(INITIAL_STATE) };
 })();
```

Not sure if there would be any performance benefits, since the function is just called N times for N instances (if I'm right...)

and yes, lowercase seems better.

Comment (wcjordan) [reply src/reducers/index.js]: Will update the variable names to be camelCase.

I don't follow the cloneDeep suggestion.  Would that provide any advantage over redeclaring?  It seems more complex.

Comment (pradeepnschrodinger) [reply src/reducers/index.js]: I just wanted to get rid of redefining but yea this seems more complex...

Btw, what about just having a cloneDeep here instead.
```javascript
function reducers(state = cloneDeep(getInitialState()), action) {
    ....
}
```
This way, there won't be any change in other lines.

Comment (wcjordan) [reply src/reducers/index.js]: Yes, that would have the same effect.  It wouldn't work over the IntegerBufferSet, but that could be pulled out.

That said, I don't think it's worth it as a solution since cloneDeep doesn't work on all arguments, and the benefit would be just minimizing this changeset.

Comment (pradeepnschrodinger) [reply src/reducers/index.js]: Ah, understood and agreed. Thanks for the explanation.

Comment (miskreant) [inline src/reducers/index.js]: Can we add a note stating that we need to be sure and return a fresh state for each table instance, so we're not using an incorrect reference for other tables that may be present.

Comment (wcjordan) [reply src/reducers/index.js]: Good idea, will do.
