### PR TITLE
Fix NPE for mouse/touch handlers in StrictMode

### LINKED ISSUE #656: Cannot read properties of null (reading 'onWheel')
**Versions**
React - 18.2.0
fixed-data-table-2 - ^1.2.11 

**Code**
```
import React from 'react'
import { Cell, Column, Table as FixedTable } from 'fixed-data-table-2'
import 'fixed-data-table-2/dist/fixed-data-table.css'

export default function Table(): JSX.Element {
  const rows = [0, 1, 2]

  return (
    <FixedTable
      rowHeight={50}
      rowsCount={rows.length}
      width={1500}
      height={800}
      headerHeight={50}
    >
      <Column
        header={<Cell>Col 1</Cell>}
        cell={<Cell>Column 1</Cell>}
        width={1000}
      />
    </FixedTable>
  )
}
```

**Error**
FixedDataTable.js:596 Uncaught TypeError: Cannot read properties of null (reading 'onWheel')

### PR DESCRIPTION
**Pull request by pradeepnschrodinger**
## Description

When React's [StrictMode](https://reactjs.org/docs/strict-mode.html) is turned on, certain methods like lifecycle methods, constructors, setState methods, etc will be double invoked (in dev mode).
In fact, in future versions, it's possible that the [same instance might be mounted/"destroyed" multiple times](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state).

In StrictMode, the order of constructor/Lifecycle methods being called changes to:
```
constructor
componentDidMount
componentWillUnmount
componentDidMount
```

However, our code in FDT is written under the assumption that life cycle methods are just called once. 
So the current code only initializes the mouse/touch handlers in the constructor, and destroys them in componentWillUnmount.
This leads to the second call to componentDidMount working with invalid mouse/touch handlers, thus causing a NPE.

## Fix
The fix was to move out initialization and cleanup to separate methods, namely `_setupHandlers` and `_cleanupHandlers`.
Setting up the handlers will be done in both the `constructor` and `componentDidMount` methods.
Cleaning up will be done in just the `componentWillUnmount` method.

I've also added guard checks to ensure we won't reinitialize/cleanup more than needed.

## Motivation

Avoid errors in future versions of React/StrictMode.
Fixes #656.

## How Has This Been Tested?

Tested in local examples as well as the repo linked in #656 (https://github.com/savaparoski/not-working)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by pradeepnschrodinger** [comment]
@Tanner-MS , do you recall if the issue in https://github.com/schrodinger/fixed-data-table-2/pull/615 was in production?
I'm trying to figure out if the issue there came due to StrictMode.

File: src/FixedDataTable.js [hunk 1]
```diff
@@ -508,43 +508,77 @@ class FixedDataTable extends React.Component {
...
   componentWillUnmount() {
+    this._cleanupHandlers();
+
+    // Cancel any pending debounced scroll handling and handle immediately.
+    this._didScrollStop.reset();
+    this._didScrollStopSync();
+  }
+
+  _setupHandlers() {
+    if (!this._wheelHandler) {
```
Comment (pradeepnschrodinger) [inline src/FixedDataTable.js:523]: I added guard checks to ensure we won't create handlers more than once.

This lets us call _setupHandlers multiple times.

File: src/FixedDataTable.js [hunk 2]
```diff
@@ -508,43 +508,77 @@ class FixedDataTable extends React.Component {
...
+        this.props.stopScrollPropagation
+      );
+    }
+
     // TODO (pradeep): Remove these and pass to our table component directly after
     // React provides an API where event handlers can be specified to be non-passive (facebook/react#6436)
-    this._divRef &&
-      this._divRef.removeEventListener('wheel', this._wheelHandler.onWheel, {
+    if (this._divRef) {
+      this._divRef.addEventListener('wheel', this._wheelHandler.onWheel, {
```
Comment (pradeepnschrodinger) [inline src/FixedDataTable.js:547]: We don't need a guard check here cause the event handler is a static function reference, so multiple `addEventListener` calls don't [add duplicate entries](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#memory_issues).

File: src/FixedDataTable.js [hunk 3]
```diff
@@ -1037,6 +1060,8 @@ class FixedDataTable extends React.Component {
     this._divRef = div;
     if (this.props.stopReactWheelPropagation) {
       this._wheelHandler.setRoot(div);
+    } else {
+      this._wheelHandler.setRoot(null);
```
Comment (pradeepnschrodinger) [inline src/FixedDataTable.js:1064]: Picked this up along the way.
Not exactly sure how we'll hit this code, but logically this just resets the root node if the prop is also reset.

**Comment by Tanner-MS** [comment]
> @Tanner-MS , do you recall if the issue in #615 was in production? I'm trying to figure out if the issue there came due to StrictMode.

Yes this was with production code.

**Comment by pradeepnschrodinger** [comment]
> Yes this was with production code.

Ah, then it's unlikely that it was the same issue mentioned here. Thanks for the confirmation.

I also see that the lifecycle methods of the components touched in #615 setup/cleanup the handlers properly, so it shouldn't be an issue, even for later versions of React.

**Comment by pradeepnschrodinger** [comment]
Released with [v1.2.12](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.2.12)
