### PR TITLE
Fix horizontal scrolling through shift key on Mac (Fixes #444)

### LINKED ISSUE #444: shift+mousewheel no longer scrolling horizontally
## Expected Behavior

Holding the `shift` key while scrolling with a mousewheel should cause the list to scroll horizontally.

## Current Behavior

During our upgrade from 0.8.13 to 0.8.23, we found that holding `shift` and using a mousewheel no longer causes the list to scroll horizontally.  

## Possible Solution

From some console.log checks, it seems that `normalizeWheel.js` is sending the correct `spinX` when holding shift, but that some other logic in `ReactWheelHandler.js` swaps it back.  I think that the break happened in https://github.com/schrodinger/fixed-data-table-2/pull/390

## Your Environment

* Version used: 0.8.23
* Browser Name and version: Chrome 74 and Safari
* Operating System and version (desktop or mobile): MacOS
* Link to your project:

### PR DESCRIPTION
**Pull request by pradeepnschrodinger**
## Description

 MacOS seems to detect shift key while scrolling, and internally swaps the spin.
The changes in #390 explicitly check for the shift key, and swaps the axis again, leading to #444.
Hence we check "navigator.platform" to disable our check for Mac.

## Motivation and Context

Fixes #444

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: src/vendor_upstream/dom/ReactWheelHandler.js [hunk 1]
```diff
@@ -129,6 +129,10 @@ class ReactWheelHandler {
       pixelY: normalizedEvent.pixelX,
     };
   }
+
+  static _allowInternalAxesSwap() /*boolean*/{
+    return navigator.platform !=="MacIntel";
```
Comment (wcjordan) [inline src/vendor_upstream/dom/ReactWheelHandler.js]: nit space after !==

**Comment by pradeepnschrodinger** [comment]
Released with v0.8.25 and v1.0.0-beta.19

We disabled FDT changing the scroll axis by it's own only for Mac.
