### PR TITLE
Fix onScrollEnd being called with outdated values (Fixes #226) (master)

### LINKED ISSUE #355: onScrollEnd is invoked with previous this.state.scrollX
## Expected Behavior
onScrollEnd is invoked with updated this.state.scrollX.

## Current Behavior
onScrollEnd is invoked with previous this.state.scrollX.

## Possible Solution
screen shot 2018-10-15 at 1 24 08 pm
line 1337, invoke `this._didScrollStop()` in setState() callback instead, something like:

```javascript
this.setState({
     scrollX: roundedX
}, this._didScrollStop);
```

So it's invoked after scrollX value is updated.

### PR DESCRIPTION
**Pull request by pradeepnschrodinger**
## Description
Upmerging the change done in #435 (which was targeted for 0.8.3-LD)

## Motivation and Context

Fixes #355

### CODE REVIEW

File: src/FixedDataTable.js [hunk 1]
```diff
@@ -596,18 +596,14 @@ var FixedDataTable = createReactClass({
   },
 
   componentWillReceiveProps(/*object*/ nextProps) {
-    var newOverflowX = nextProps.overflowX;
```
Comment (pradeepnschrodinger) [inline src/FixedDataTable.js]: unrelated
these were never used

**Comment by wcjordan** [comment]
Is this the same as what we did for our custom LD branch?

**Comment by pradeepnschrodinger** [comment]
> Is this the same as what we did for our custom LD branch?

yep, (discarding the unused variables that got removed)
