### PR TITLE
Expose cell visibility information to cell renderers

### LINKED ISSUE #650: Check the column/cell visibility
I want to do certain actions when an item is visible in viewport, but the column or cell component does not return any visibility value so i have to create my own onViewport hook in each cell, which affects the performance.

## Expected Behavior
To return a visible tag from Column that I can pass to header cell and body cell

## Current Behavior
i see the visible: true/false in the higher component of Column, but we cant pull that value.

## Possible Solution
we can get the visible value from the cell prop or headerCell prop from the Column

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
N/A

* Version used: 1.1.3
* Browser Name and version: Chrome 103.0.5060.53 
* Operating System and version (desktop or mobile): Mac M1 Monterey
* Link to your project: N/A

### PR DESCRIPTION
**Pull request by pradeepnschrodinger**
## Description

Not all cells rendered by FDT are visible to the user.
eg: Cells for columns outside the viewport will be rendered if `allowCellsRecycling` column prop is turned off. 
Similarly, if the user has specified a positive value for `bufferRowCount`, then FDT prerenders a given count of rows before/after the viewport.

I'm adding a new cell prop `isVisible`, which can be used to figure out if the rendered cell is visible to the user.

## Motivation and Context

Fixes #650, where the user wanted to run some side effects for a cell based on whether it's visible or not.

## How Has This Been Tested?

Tested using our local examples.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: src/FixedDataTableCell.js [hunk 1]
```diff
@@ -289,6 +305,7 @@ class FixedDataTableCell extends React.Component {
       columnKey,
       height,
       width,
+      isVisible,
```
Comment (pradeepnschrodinger) [inline src/FixedDataTableCell.js:308]: This exposes `isVisible` to the cell renderers.

File: src/FixedDataTableCellGroup.js [hunk 2]
```diff
@@ -183,6 +186,7 @@ class FixedDataTableCellGroupImpl extends React.Component {
         columnGroupWidth={columnGroupWidth}
         pureRendering={pureRendering}
         isRTL={this.props.isRTL}
+        isVisible={this.props.isVisible && isHorizontallyVisible}
```
Comment (pradeepnschrodinger) [inline src/FixedDataTableCellGroup.js:189]: At this component level, `props.isVisible` refers to whether the cell group is vertically visible.
This combined with `isHorizontallyVisible` determines whether the individual cell is within the viewport.

File: src/FixedDataTableRow.js [hunk 3]
```diff
@@ -170,8 +170,12 @@ class FixedDataTableRowImpl extends React.Component {
       return true;
     }
 
-    // if row is not visible then no need to render it
-    // change in visibility is handled by the parent
+    // if row's visibility has changed, then update it
+    if (this.props.visible !== nextProps.visible) {
```
Comment (pradeepnschrodinger) [inline src/FixedDataTableRow.js:174]: Rerender the component when visibility changes, similar to the [usage here](https://github.com/schrodinger/fixed-data-table-2/blob/afbc448ba4dae70e9591e24e550f6cebc1081c12/src/FixedDataTableRow.js#L538-L546).

File: src/FixedDataTableCell.js [hunk 4]
```diff
@@ -96,7 +101,11 @@ class FixedDataTableCell extends React.Component {
   };
 
   shouldComponentUpdate(nextProps) {
-    if (nextProps.isScrolling && this.props.rowIndex === nextProps.rowIndex) {
+    if (
+      nextProps.isScrolling &&
+      this.props.rowIndex === nextProps.rowIndex &&
+      this.props.isVisible === nextProps.isVisible
```
Comment (pradeepnschrodinger) [inline src/FixedDataTableCell.js:107]: Ensure cell is rerendered whenever visibility changes.

**Comment by pradeepnschrodinger** [comment]
Released with [v.1.2.13](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.2.13)

**Comment by Tanner-MS** [comment]
Is this not a breaking change? If someone was using the Cell component now there is a required isVisible prop?

Also while uptaking this change I ran into the following issue:
image
Where the propType for the FixedDataTableCellDefaultDeprecated.js should be bool instead of boolean

**Comment by pradeepnschrodinger** [comment]
> Is this not a breaking change? If someone was using the Cell component now there is a required isVisible prop?

Good question. The new prop is not marked as `required` in the exposed/optional cell renderers (`FixedDataTableCellDefault` and `FixedDataTableCellDefaultDeprecated`), so it shouldn't be an issue.

It's only `required` in internal components that FDT renders directly (like `FixedDataTableCell`), so the prop should always be defined.

> Also while uptaking this change I ran into the following issue: image Where the propType for the FixedDataTableCellDefaultDeprecated.js should be bool instead of boolean

Nice catch! I can put up a hotfix and bump up the release.

**Comment by pradeepnschrodinger** [comment]
@Tanner-MS , I fixed the PropTypes typo through https://github.com/schrodinger/fixed-data-table-2/commit/bc27879edcc8e49ddf5d0b5f63e95770ff6e819f, which is available on [v1.2.15](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.2.15).
