### PR TITLE
Make onWheel handler passive for scrollbar (Fixes #427)

### LINKED ISSUE #427: More scrolling errors in Chrome 73
This issue is related to #407 (Scrolling errors in Chrome).

The problem still occurs in the current Version (v0.8.21) when scrolling by mouse wheel while hovering over the scrollbar of the fixed-data-table2. 

## Expected Behavior
No warning messages should be displayed in Chrome >=73 while scrolling by mouse wheel while hovering over the scrollbar

## Current Behavior
Warning messages are displayed in the Chrome Console:
`[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See <URL>`

## Possible Solution
I will provide a pull request

## Steps to Reproduce (for bugs)
- Place mouse over scrollbar of fixed-data-table2
- Scroll with mouse wheel

## Your Environment
* Version used: v0.8.21
* Browser Name and version: Chrome 73

### PR DESCRIPTION
**Pull request by stues**
## Description
Removed the react `onWheel` handler within scrollbar and added a passive native which removes scrolling error errors in Chrome 73+

## Motivation and Context
Fixes Issue #427 (log erros in Chrome 73+)

## How Has This Been Tested?
- Run multiple manual scroll tests

## Screenshots (if appropriate):
-

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by wcjordan** [comment]
Good catch!  This looks good at a glance.

@pradeepnschrodinger could you review and merge when you have a chance?

File: src/Scrollbar.js [hunk 1]
```diff
@@ -209,6 +208,10 @@ var Scrollbar = createReactClass({
   },
 
   componentDidMount() {
+    this.root && this.root.addEventListener('wheel',
```
Comment (pradeepnschrodinger) [inline src/Scrollbar.js]: can you put `'wheel'` on a new line

**Comment by pradeepnschrodinger** [comment]
Released with [v0.8.22](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v0.8.22) and [v1.0.0-beta.17](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.17)
