### PR TITLE
Fix table scrolling while touch scroll is disabled (master)

### LINKED ISSUE #456: Horizontal scrolling is buggy on mobile
## Expected Behavior
On mobile devices, the user should be able to scroll horizontally within the table.

## Current Behavior
The table only scrolls forwards, never backwards, and even then, it's quite laggy.

## Steps to Reproduce (for bugs)
Use Chrome's device emulator here http://schrodinger.github.io/fixed-data-table-2/example-object-data.html

## Context
Our users aren't able to scroll the table horizontally on mobile devices.

## Your Environment
Any environment can be used, I think, since the examples are behaving exactly as in our application.

### PR DESCRIPTION
**Pull request by pradeepnschrodinger**
## Description

Touch handlers are registered even when 'touchScrollEnabled' is not true. This allows users to scroll the table (incorrectly) by touch, leading to #456 

## Motivation and Context

Fixes #456 
Also fixes scroll bar not being in the correct position

## How Has This Been Tested?

Existing examples (both emulator and normal mode).
Object Data Example and Touch Scroll Example

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: src/Scrollbar.js [hunk 1]
```diff
@@ -37,11 +37,11 @@ var KEYBOARD_SCROLL_AMOUNT = 40;
 var _lastScrolledScrollbar = null;
 
 var getTouchX = function(e) {
-  return Math.round(e.targetTouches[0].pageX - e.target.getBoundingClientRect().x);
+  return Math.round(e.targetTouches[0].clientX - e.target.getBoundingClientRect().x);
```
Comment (pradeepnschrodinger) [inline src/Scrollbar.js]: https://stackoverflow.com/a/9335517
