### PR TITLE
Viewport row buffering while scrolling (third iteration)

### LINKED ISSUE #402: Implement viewport row buffering while scrolling
The master branch doesn't update buffered rows if they fall outside the viewport while scrolling. The beta branch, however, updates ALL the buffered rows regardless of scrolling.

## Expected Behavior
Beta does the above optimization and saves lot of render time (usually dependent on rows within the view port).

The black window covers the total rows rendered by FDT. 
The green rows represents the total rows that lies within the viewport.
The red rows represents the lows that's outside the viewport.
fdt scroll buffer story
_(Kind of an ugly pic)_
The red rows are the problem here. In beta, these are updated regardless of scrolling, whereas Master cleverly handles their update only after the scroll is finished. This makes sense as the user won't be seeing them anyway and there's a high chance for them to disappear while scrolling is in progress.

## Current Behavior
Beta is kind of slow because of this.

## Possible Solution
While scrolling is turned on, only update the buffered rows which lie within the view port.

## Steps to Reproduce (for bugs)

In FixedDataTableBufferedRows.js, add the following POC in the render method.

```js
    const oldMap = this._staticRowArray.map((o) => {
      return [o.key, o.props.index];
    });

   // ...
   // ... existing code which updates this_staticRowArray
   // ...

    const newMap = this._staticRowArray.map((o) => {
      return [o.key, o.props.index];
    });

    oldMap.sort((a, b) => (a.props || {}).index < (b.props || {}).index);
    newMap.sort((a, b) => (a.props || {}).index < (b.props || {}).index);
    const changedMap = [];
    oldMap.forEach((x, i, a) => {
        if (oldMap[i][1] != newMap[i][1]) {
          changedMap.push([oldMap[i][1], newMap[i][1]]);
        }
      }
    );
    
    console.log('Updated buffer length = ', changedMap.length);
    console.log('Actual Buffer length = ', this._staticRowArray.length);
```

In master, you'll that only half the buffered rows got updated while scrolling. And the remaining get's updated while scrolling is finished.

## Context
Should solve lot of scroll related performance issues in beta.

## Your Environment
* Version used: v1.0.0.12-beta
* Browser Name and version: Google Chrome (lastest)
* Operating System and version (desktop or mobile): Windows 10
* Link to your project: <Our own Examples>

### PR DESCRIPTION
**Pull request by pradeepnschrodinger**
Implement viewport row buffering while scrolling.

## Description
See #402

## Motivation and Context
Fixes #402

## How Has This Been Tested?

Just manual testing done on dynamic height rows.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: src/FixedDataTableBufferedRows.js [hunk 1]
```diff
@@ -78,27 +81,32 @@ class FixedDataTableBufferedRows extends React.Component {
...
     var baseOffsetTop = props.offsetTop - props.scrollTop;
 
-    for (let i = 0; i < rowsToRender.length; ++i) {
+    for (let i = 0; i < rowsToRender.length; i++) {
       const rowIndex = rowsToRender[i];
+
+      // if the row doesn't exist in the buffer, assign a fake row to it.
+      // this is so that we can get rid of unnecessary row mounts/unmounts
       if (rowIndex === undefined) {
-        this._staticRowArray[i] = (
```
Comment (pradeepnschrodinger) [inline src/FixedDataTableBufferedRows.js]: moved these kind of row creation logic into this.getFakeRow (see [comment](https://github.com/schrodinger/fixed-data-table-2/pull/415#discussion_r270716208))

File: src/FixedDataTableRow.js [hunk 2]
```diff
@@ -452,22 +457,21 @@ class FixedDataTableRow extends React.Component {
       width: this.props.width,
       height: this.props.height,
       zIndex: (this.props.zIndex ? this.props.zIndex : 0),
+      display: (this.props.visible ? 'block' : 'none'),
     };
     FixedDataTableTranslateDOMPosition(style, 0, this.props.offsetTop, this._initialRender);
 
+    const { offsetTop, zIndex, visible, ...rowProps } = this.props;
```
Comment (pradeepnschrodinger) [inline src/FixedDataTableRow.js]: Cleanup for https://github.com/schrodinger/fixed-data-table-2/pull/415#discussion_r270631650

File: src/reducers/computeRenderedRows.js [hunk 3]
```diff
@@ -55,7 +55,8 @@ export default function computeRenderedRows(state, scrollAnchor) {
     newState.firstRowOffset = 0;
   }
 
-  computeRenderedRowOffsets(newState, rowRange);
+  computeRenderedRowOffsets(newState, rowRange, state.scrolling);
```
Comment (pradeepnschrodinger) [inline src/reducers/computeRenderedRows.js]: cleanup for:
* https://github.com/schrodinger/fixed-data-table-2/pull/415#discussion_r269329250
* https://github.com/schrodinger/fixed-data-table-2/pull/415#discussion_r269329945

File: src/FixedDataTableBufferedRows.js [hunk 4]
```diff
@@ -78,27 +81,32 @@ class FixedDataTableBufferedRows extends React.Component {
...
+        }
+      });
+    } else {
+      this._staticRowArray.length = rowsToRender.length;
+    }
+
     var baseOffsetTop = props.offsetTop - props.scrollTop;
 
-    for (let i = 0; i < rowsToRender.length; ++i) {
+    for (let i = 0; i < rowsToRender.length; i++) {
```
Comment (wcjordan) [inline src/FixedDataTableBufferedRows.js]: From the previous review:
> Since we use a forEach, only defined values (rows) are iterated over.

forEach also includes undefined values.  Try `[0, '0', undefined, null, 1, '1'].forEach(console.log)`

Thanks for adding back the undefined handling

File: src/FixedDataTableBufferedRows.js [hunk 5]
```diff
@@ -78,27 +81,32 @@ class FixedDataTableBufferedRows extends React.Component {
     var rowClassNameGetter = props.rowClassNameGetter || emptyFunction;
     var rowsToRender = this.props.rowsToRender || [];
 
-    this._staticRowArray.length = rowsToRender.length;
+    if (props.isScrolling) {
+      // we are scrolling, so don't display any rows which lie outside the viewport
```
Comment (wcjordan) [inline src/FixedDataTableBufferedRows.js]: Maybe also mention it's still important to render them so we don't cause mounts & unmounts

**Comment by wcjordan** [comment]
lgtm.  Be sure to test it out and ensure it achieves the perf improvements we're looking for / they weren't lost in the CR changes

File: src/FixedDataTableBufferedRows.js (hunk 4 above)
Comment (pradeepnschrodinger) [reply src/FixedDataTableBufferedRows.js]: Aah my bad, I totally wrote that wrong.
What I meant was that only indices assigned are iterated.
```
a = [];
a[0] = 0;
a[1] = 1;
a[3] = 3;
a.forEach(console.log); // won't iterate for a[2].
```

File: src/FixedDataTableBufferedRows.js (hunk 5 above)
Comment (pradeepnschrodinger) [reply src/FixedDataTableBufferedRows.js]: Sure will do

File: src/FixedDataTableBufferedRows.js (hunk 4 above)
Comment (wcjordan) [reply src/FixedDataTableBufferedRows.js]: ah okay that makes sense.  As long as everything still works if we have
a[2] = undefined;
