### PR TITLE
Polyfill `globalThis`

### LINKED ISSUE #673: "Global is not defined" in React Vite app
Fixed-data-table-2 does not work in Vite-React setup. 

## Expected Behavior
Application works. 

## Current Behavior
image
Error: 

```
nativeRequestAnimationFrame.js:18 Uncaught ReferenceError: global is not defined
    at node_modules/fixed-data-table-2/internal/vendor_upstream/core/nativeRequestAnimationFrame.js (nativeRequestAnimationFrame.js:18:35)
    at __require (chunk-J43GMYXM.js?v=ed8548d7:11:50)
    at node_modules/fixed-data-table-2/internal/vendor_upstream/core/requestAnimationFramePolyfill.js (requestAnimationFramePolyfill.js:10:59)
    at __require (chunk-J43GMYXM.js?v=ed8548d7:11:50)
    at node_modules/fixed-data-table-2/internal/vendor_upstream/dom/ReactWheelHandler.js (ReactWheelHandler.js:26:61)
    at __require (chunk-J43GMYXM.js?v=ed8548d7:11:50)
    at node_modules/fixed-data-table-2/internal/FixedDataTable.js (FixedDataTable.js:24:49)
    at __require (chunk-J43GMYXM.js?v=ed8548d7:11:50)
    at node_modules/fixed-data-table-2/internal/FixedDataTableContainer.js (FixedDataTableContainer.js:24:46)
    at __require (chunk-J43GMYXM.js?v=ed8548d7:11:50)
```
## Possible Solution
Since Vite is getting traction, it would be nice to have the solution for the growing platform. If something is missing in the configuration, it would ne good to specify it in the docs. 

## Steps to Reproduce (for bugs)
1. setup vite+react+ts project
2. add fixed-data-table-2
3. use Table component

## Your Environment

Chrome: 109.0.5414.121

package.json(default + fixed-table) : 

```
{
  "name": "react-vite",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc && vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "fixed-data-table-2": "^1.2.16",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
  },
  "devDependencies": {
    "@types/fixed-data-table-2": "^0.8.8",
    "@types/react": "^18.0.24",
    "@types/react-dom": "^18.0.8",
    "@vitejs/plugin-react": "^2.2.0",
    "eslint": "8.22.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-config-react-app": "^7.0.1",
    "prettier": "^2.8.0",
    "typescript": "^4.6.4",
    "vite": "^3.2.3"
  }
}
```

vite config (default): 

```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()]
})
```

### PR DESCRIPTION
**Pull request by pradeepnschrodinger**
## Description

Some of our old vendors/third-party code tries to reference `global` which don't really exist in browser environments.

This PR change usages from `global` to the more upto standard [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis), which works across different environments like node, browser, workers, etc.
However, `globalThis` is not supported in old browsers (like IE 11), so I'm also adding something like a polyfill to make sure that `globalThis` defaults back to `window`, `global`, `self`, etc which are the global objects in various environments.

## Motivation and Context

Fixes #673.
React-vite doesn't seem to define or shim `global`, so trying to render FDT-2 in this environment throws a NPE.

## How Has This Been Tested?

Tested this out in local examples. 
Also tested in a minimal react-vite boilerplate code that just imported FDT-2 and rendered a basic table.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: src/vendor_upstream/core/globalThisPolyfill.js [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ * This source code is licensed under the BSD-style license found in the
+ * LICENSE file in the root directory of this source tree. An additional grant
+ * of patent rights can be found in the PATENTS file in the same directory.
+ *
+ * @providesModule globalThisPolyfill
+ */
+
+const globalThis =
+  typeof globalThis !== 'undefined'
+    ? globalThis
```
Comment (AmanGupta2708) [inline src/vendor_upstream/core/globalThisPolyfill.js:14]: How this statement is working ?, Directly executing this command in console throws error -: "globalThis is not defined".

Comment (pradeepnschrodinger) [reply src/vendor_upstream/core/globalThisPolyfill.js:14]: Good catch. FWIW, this works in compiled code since it uses `var` instead of `const`.
I'll fix this.

Comment (pradeepnschrodinger) [reply src/vendor_upstream/core/globalThisPolyfill.js:14]: Fixed

File: src/vendor_upstream/core/globalThisPolyfill.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+ * All rights reserved.
+ *
+ * This source code is licensed under the BSD-style license found in the
+ * LICENSE file in the root directory of this source tree. An additional grant
+ * of patent rights can be found in the PATENTS file in the same directory.
+ *
+ * @providesModule globalThisPolyfill
+ */
+
+const globalThisPolyfill =
```
Comment (AmanGupta2708) [inline src/vendor_upstream/core/globalThisPolyfill.js:12]: nit: can we simply write it like this` const globalThisPolyFill = globalThis || window || global || self || {} `

Comment (pradeepnschrodinger) [reply src/vendor_upstream/core/globalThisPolyfill.js:12]: Unfortunately that won't work if any of these are not defined.

**Comment by AmanGupta2708** [comment]
LGTM

**Review by AmanGupta2708 — APPROVED** [review]
