### PR TITLE
Fix prop type warning when rows are empty - beta

### LINKED ISSUE #433: Empty table throws propTypes warning
## Expected Behavior
When I render table with zero rows (`rowsCount` equal to `0`), table should be rendered without a warning.

## Current Behavior
When I render following table:
```
 <Table
    rowsCount={ 0 }
    rowHeight={ 50 }
    width={ 1000 }
    height={ 500 }
    headerHeight={ 100 }
  >
    <Column
      header={ <Cell>Header</Cell> }
      cell={ <Cell>Basic content</Cell> }
      width={ 200 }
    />
  </Table>
```
it throws following warning:
```
Warning: Failed prop type: The prop `endViewportRowIndex` is marked as required in `FixedDataTableBufferedRows`, but its value is `undefined`.
    in FixedDataTableBufferedRows (created by FixedDataTable)
    in FixedDataTable (created by FixedDataTableContainer)
    in FixedDataTableContainer
```

## Your Environment
* Version used: **1.0.0-beta.17**
* Browser Name and version: **Google Chrome (73.0.3683.103)**
* Operating System and version (desktop or mobile): **Windows 10 - Desktop**

### PR DESCRIPTION
**Pull request by pradeepnschrodinger**
## Description

Edge case when FDT was rendered with empty rows.
endViewPortRowIndex wasn't assigned in computeRenderedRows. 
Introduced through #421.

## Motivation and Context

Fixes #433 

## How Has This Been Tested?

Existing examples

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: src/reducers/computeRenderedRows.js [hunk 1]
```diff
@@ -101,6 +111,7 @@ function calculateRenderedRowRange(state, scrollAnchor) {
       endBufferIdx: 0,
```
Comment (pradeepnschrodinger) [inline src/reducers/computeRenderedRows.js]: the early return here meant that we didn't assign to the state... so instead of assigning these to the state here and down below, I moved them both back to the caller.

File: src/reducers/computeRenderedRows.js [hunk 2]
```diff
@@ -163,13 +174,11 @@ function calculateRenderedRowRange(state, scrollAnchor) {
     }
   }
 
-  state.firstRowIndex = firstViewportIdx;
```
Comment (pradeepnschrodinger) [inline src/reducers/computeRenderedRows.js]: moved back to caller. 

@wcjordan, sometimes it's hard to read through the code and see which state gets changed since a lot of functions mutate state directly. It's safe in our usages since state is always cloned, but just returning the value and then assigning it on the parent looks cleaner in places like this. Thoughts?

**Comment by pradeepnschrodinger** [comment]
Released with [v1.0.0-beta.18](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v1.0.0-beta.18)
