### PR TITLE
Fix touch handlers and make them passive

### LINKED ISSUE #705: Column resize doesn't properly work on mobile
Dragging to resize a column on mobile doesn't work on a new project using your project as a library

But If I check out your project (on the master branch) and I run your examples (using ```yarn site-dev-server``` ) from there the resize is working ok on mobile

## Expected Behavior
After touch down, when touch moves, the resize line should move and when touching up the column should get resized 

## Current Behavior
When dragging for resizing a column on mobile, the resize line doesn't move and  when touch up, the column doesn't resize. If you tap second time the column gets resized. 

## Steps to Reproduce (for bugs)
1. You should open the following link in chrome
https://codesandbox.io/s/exciting-meitner-9qjjqf?file=/src/index.js

2. Use the mobile mode of the chrome dev tools
image

3. Resizing a column doesn't work

## Your Environment
* Version used: latest (2.0.2)
* Browser Name and version: Chrome Version 119.0.6045.123

### PR DESCRIPTION
**Pull request by pradeepnschrodinger**
## Description

Touch support in FDT v2 is wonky. 
There's multiple issues here:

## problem 1
We're no longer passing down the `touchEnabled` prop to the [cell renderers](https://github.com/schrodinger/fixed-data-table-2/blob/28e518a95e78fdefe3536befec580afa3add68d5/src/FixedDataTableCell.js#L207-L217) within FDT.
But the resizer plugin `<ResizeCell />` still [expects it](https://github.com/schrodinger/fixed-data-table-2/blob/28e518a95e78fdefe3536befec580afa3add68d5/src/plugins/ResizeReorder/ResizerKnob.js#L88-L90), making it not work for touch devices.

## problem 2
The touch/mouse related event listeners were treated as passive. 
This is a problem with React not yet having an API for clients to specify event listener options.

FDT relies on stopping propagation or preventing default behavior of these events in various places, and they did not work as expected.
I'm fixing this by manually registering the handlers via `addEventListener` with the [`passive`](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#passive) property turned OFF.
See facebook/react#6436

## problem 3
Sometimes, the first touch events don't seem to work unless the user does a follow-up click.
One particular case is when the user clicks on the reorder knob; FDT will render a "drag proxy" which replaces the original cell thus making the original touch event (which relies on the original cell to be in the document tree) to not work properly.

The docs explain this nicely: https://developer.mozilla.org/en-US/docs/Web/API/Touch/target

> The read-only target property of the Touch interface returns the ([EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget)) on which the touch contact started when it was first placed on the surface, even if the touch point has since moved outside the interactive area of that element or even been removed from the document. **Note that if the target element is removed from the document, events will still be targeted at it, and hence won't necessarily bubble up to the window or document anymore.** If there is any risk of an element being removed while it is being touched, the best practice is to attach the touch listeners directly to the target.

## problem 4
`<ReorderCell />` accidentally renders the children twice in some cases because we accidentally passed its' children to its child renderer...
Check this [comment](https://github.com/schrodinger/fixed-data-table-2/pull/706#discussion_r1389857673) for details.

## Motivation and Context

Fixes #705 

## How Has This Been Tested?

Tested with local examples, and also on codesandbox: https://codesandbox.io/s/fixed-data-table-2-touch-resizing-s22nn7
TODO: Test within LiveDesign

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

File: examples/ColumnGroupsResizeReorderExample.js [hunk 1]
```diff
@@ -156,6 +156,7 @@ class ColumnGroupsExample extends React.Component {
         rowsCount={dataList.getSize()}
         width={1000}
         height={500}
+        touchScrollEnabled={true}
```
Comment (pradeepnschrodinger) [inline examples/ColumnGroupsResizeReorderExample.js:159]: Updated resize-reorder column group example to work on touch devices

File: src/plugins/ResizeReorder/ResizerKnob.js [hunk 2]
```diff
@@ -82,18 +88,56 @@ class ResizerKnob extends React.PureComponent {
     return (
       <div
         className={cx('fixedDataTableCellLayout/columnResizerContainer')}
-        ref={(element) => (this.curRef = element)}
+        ref={this.setResizerKnobRef}
         style={resizerKnobStyle}
-        onMouseDown={this.onMouseDown}
-        onTouchStart={this.props.touchEnabled ? this.onMouseDown : null}
-        onTouchEnd={this.props.touchEnabled ? this.suppressEvent : null}
-        onTouchMove={this.props.touchEnabled ? this.suppressEvent : null}
```
Comment (pradeepnschrodinger) [inline src/plugins/ResizeReorder/ResizerKnob.js:90]: Same reasoning as above. 
I moved the registration to `setupHandlers()` and deregistration to `cleanupHandlers`.

File: src/vendor_upstream/dom/DOMMouseMoveTracker.js [hunk 3]
```diff
@@ -86,17 +86,20 @@ class DOMMouseMoveTracker {
...
+        this._onMouseMove,
+        { passive: false }
       );
       this._eventTouchEndToken = EventListener.listen(
-        this._domNode,
+        event.target,
         'touchend',
-        this._onMouseUp
+        this._onMouseUp,
+        { passive: false }
```
Comment (pradeepnschrodinger) [inline src/vendor_upstream/dom/DOMMouseMoveTracker.js:102]: I'm registering these at the source element that triggered the touch (i.e, `event.target`) so we don't abruptly loose the touch handling just because the source element got removed.

TODO: Add a comment explaining this and link to moz docs.

File: src/vendor_upstream/stubs/EventListener.js [hunk 4]
```diff
@@ -23,14 +23,15 @@ const EventListener = {
    * @param {DOMEventTarget} target DOM element to register listener on.
    * @param {string} eventType Event type, e.g. 'click' or 'mouseover'.
    * @param {function} callback Callback function.
+   * @param {object} options Extra options to customize the listener
    * @return {object} Object with a `remove` method.
    */
-  listen(target, eventType, callback) {
+  listen(target, eventType, callback, options = {}) {
```
Comment (pradeepnschrodinger) [inline src/vendor_upstream/stubs/EventListener.js:29]: Added options param to let the caller customize the listener.

File: src/FixedDataTableCellDefault.js [hunk 5]
```diff
@@ -91,6 +91,7 @@ class FixedDataTableCellDefault extends React.Component {
       isGroupHeader,
       maxWidth,
       minWidth,
+      touchEnabled,
```
[the remark this answers is not in the document]
Comment (karry08) [reply src/FixedDataTableCellDefault.js:94]: does it cause an issue?

**Review by karry08 — APPROVED** [review]
LGTM

**Comment by pradeepnschrodinger** [comment]
Release with [v2.0.3](https://github.com/schrodinger/fixed-data-table-2/releases/tag/v2.0.3).
